/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package leap.year;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        LeapYear leapyear = new LeapYear();

        int year = 0;

        System.out.println("Enter a Year :");
        Scanner sc = new Scanner(System.in);
        year = sc.nextInt();

        System.out.println(leapyear.isLeapYear(year));
    }
}
