/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package string.calculator;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        StringCalculator stringcalculator = new StringCalculator();

        String numbers = "";

        System.out.println("Enter a number (String)");
        Scanner sc = new Scanner(System.in);
        numbers = sc.nextLine();

        System.out.println(stringcalculator.add(numbers));
    }
}
